### PR TITLE
feat(config): add bicep comment string

### PR DESCRIPTION
**Pull request by kksat**
## Description

Add comment string for bicep files 

see https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/file#comments

## Related Issue(s)
NA
## Screenshots
NA

### CODE REVIEW

**Comment by kksat** [comment]
@folke what should be done to merge this PR?

**Comment by folke** [comment]
Fix the code? See tests

**Comment by folke** [comment]
ty!

**Comment by kksat** [comment]
Thank you!

**Pull request merged**
